[package]
name = "cyndra-secrets"
version = "0.38.0"
edition = "2021"
license = "Apache-2.0"
description = "Plugin to for managing secrets on cyndra"
keywords = ["cyndra-service", "secrets"]

[dependencies]
async-trait = "0.1.56"
cyndra-service = { path = "../../service", version = "0.38.0" }
